# site settings
title: Putri Amalina Agestya
subtitle: by HTML5 UP
email: putri15amalina8agestya@gmail.com
description: Putri's Personal Website
baseurl: "/putriamalina.github.io" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Putri Amalina Agestya
street_address: Cikaret, Cibinong
city: Bogor
state: Jawa Barat
zip_code: 16914
country: Indonesia
phone: (62) 8111108158

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/putriamalina
  Instagram: https://instagram.com/puutriamalina
  LinkedIn: https://www.linkedin.com/in/putri-amalina-agestya-b01111215

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
